services:
    mariadb:
        build:
            context: ./mariadb-custom
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        volumes:
            - ./mariadb:/var/lib/mysql

    web:
        image: dolibarr/dolibarr:20.0.0
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://127.0.0.1'
            DOLI_ADMIN_LOGIN: 'admin'
            DOLI_ADMIN_PASSWORD: 'admin'
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
        ports:
            - "80:80"
        links:
            - mariadb
        volumes:
            - ./dolibarr_documents:/var/www/documents
            - ./dolibarr_custom:/var/www/html/custom